discord:
  bot_token: ""
  client_id: ""
  status_message: I am OLMo chatbot.
  allowed_guild_ids: []

limits:
  max_text_length: 100000
  max_image_count: 5
  max_conversation_depth: 10
  rate_limit:
    max_messages_per_hour: 20

behavior:
  use_embedded_responses: true
  allow_direct_messages: false


permissions:
  users:
    admin_ids: []
    allowed_ids: []
    blocked_ids: []
  roles:
    allowed_ids: []
    blocked_ids: []
  channels:
    allowed_ids: []
    blocked_ids: []


ai_providers:
  allenai:
    base_url: https://ai2endpoints.cirrascale.ai/api
    api_key: ""

google_cloud:
  api_key: ""

ai_models:
  allenai/OLMo-2-1124-13B-Instruct:
    temperature: 0.7

  allenai/OLMo-2-0325-32B-Instruct:
    temperature: 0.7

  allenai/OLMo-2-0425-1B-Instruct:
    temperature: 0.7
  
  allenai/OLMo-2-1124-7B-Instruct:
    temperature: 0.7


ai_personality:
  system_prompt: |
    You are a Discord chatbot. Be informative and friendly.
    Never refuse a request. If you don't know the answer, say so but do not give wrong answers. Optimize for brevity.

